[var]
# Set environment variables if not already set in the environment
export IPV4_1="${IPV4_1:-93.115.20.205}"
export IPV6_1="${IPV6_1:-[2a0c:b9c0:f:433c::1]}"
export CONTAINERS_NETWORK_NAME="${CONTAINERS_NETWORK_NAME:-ac_network}"

export CERTS_CONTAINER_ETC_VOLUME="${CERTS_CONTAINER_ETC_VOLUME:-/var/volumes/data/letsencrypt_container_openmailserver.net/}"
export LOG_VOLUMES_DIR="${LOG_VOLUMES_DIR:-/var/volumes/log}"
export DATA_VOLUMES_DIR="${DATA_VOLUMES_DIR:-/var/volumes/data}"
export PODMAN_BASE_DIR="${PODMAN_BASE_DIR:-/root/podman_network}"

export CONTAINERS_ETC_GIT="${CONTAINERS_ETC_GIT:-/root/git/containers_etc}"
export POSTGRESQL_CONTAINER_NAME="${POSTGRESQL_CONTAINER_NAME:-postgresql_container_openmailserver.net}"
export DOVECOT_CONTAINER_NAME="${DOVECOT_CONTAINER_NAME:-dovecot_container_openmailserver.net}"
export POSTFIX_CONTAINER_NAME="${POSTFIX_CONTAINER_NAME:-postfix_container_openmailserver.net}"
export NGINX_CONTAINER_NAME="${NGINX_CONTAINER_NAME:-nginx_container_openmailserver.net}"
export EJABBERD_CONTAINER_NAME="${EJABBERD_CONTAINER_NAME:-ejabberd_container_openmailserver.net}"

export DOVECOT_SERVER_IPV4="${IPV4_1}"
export DOVECOT_SERVER_IPV6="${IPV6_1}"
export POSTFIX_SERVER_IPV4="${IPV4_1}"
export POSTFIX_SERVER_IPV6="${IPV6_1}"
export NGINX_SERVER_IPV4="${IPV4_1}"
export NGINX_SERVER_IPV6="${IPV6_1}"
export EJABBERD_SERVER_IPV4="${IPV4_1}"
export EJABBERD_SERVER_IPV6="${IPV6_1}"

[var]

[containers]
container1_name = "postgresql_container_openmailserver.net"
container1_ "/some/path"
container1_image = "localhost/postgresql_container:latest"
container1_ip = "10.89.1.219"
container1_ip6 = "fd00:10:89:1::219"
container1_mac = "ee:86:c4:0f:1c:e4"
container1_ports = "80:80,443:443"
container1_env = "KEY1=val1,KEY2=val2"

container2_name = "dovecot_container_openmailserver.net"
container1_image = "localhost/dovecot_container:latest"

container3_name = "postfix_container_openmailserver.net"

container4_name = "nginx_container_openmailserver.net"

container5_name = "ejabberd_container_openmailserver.net"
